#   file: Containerfile
# author: simshadows <contact@simshadows.com>

FROM python:3.14-bookworm

#ENV TZ="Australia/Sydney"

# vim is useful for debugging
RUN apt-get update
RUN apt-get install -y vim

RUN useradd -m -s /bin/bash user

# repo folder to be a mount point
RUN mkdir -p /repo
RUN chown user /repo
WORKDIR /repo

USER user

ENV PATH="/home/user/.local/bin:${PATH}"

# Install uv
# (TODO: When uv is available, install that way instead)
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# Install Claude Code
RUN curl -fsSL https://claude.ai/install.sh | bash
RUN echo '' >> ~/.bashrc
RUN echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc
# .claude folder to be a mount point
RUN mkdir -p /home/user/.claude

ENTRYPOINT sleep infinity
